server:
  port: 9013

spring:
  application:
    name: virtual-cnc

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true

multiplicationHost: http://${GATEWAY_HOST:localhost}:8000/api/v1
